[package]
name = "command-line"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
console = "0.16.1"
dialoguer = "0.12.0"
indicatif = "0.18.2"
tabled = "0.20.0"
tokio = { version = "1.48.0", features = ["full"] }
