[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true

[watch]
watch = []
ignore = []

[serve]
addresses = ["0.0.0.0"]
port = 8000
open = false
