[package]
name = "programming-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
futures = "0.3.31"
num = "0.4.3"
rand = "0.9.2"
regex = "1.12.2"
tokio = { version = "1.48.0", features = ["full"] }
