[tasks.dev]
command = "trunk"
args = ["serve", "--port=8000"]

[tasks.build]
command = "trunk"
args = ["build", "--release"]

[tasks.preview]
command = "static-web-server"
args = ["--port=8080", "--root=./dist", "--page-fallback=index.html"]
